# Generated by Django 2.2.8 on 2021-08-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0018_auto_20210804_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reminders',
            name='time',
        ),
        migrations.AddField(
            model_name='reminders',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
