# Generated by Django 2.2.8 on 2021-08-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0019_auto_20210804_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminders',
            old_name='datetime',
            new_name='dateNtime',
        ),
    ]
